import chantha from './assets/chantha.JPG';
import ibrahim from './assets/ibes.JPG';
import jerry from './assets/jerry.JPG';
import mare from './assets/mariana.JPG';
import vyas from './assets/vyas.JPG';
import user from './assets/user.png';
import dr_yun from './assets/dr_yun.jpg';

const officers = [
	// {
	// 	id: 0,
	// 	name: 'Dr.Chang Yun',
	// 	image: dr_yun,
	// 	linkedin: 'https://www.linkedin.com/in/chang-yun-94340a14/',
	// 	email: 'phys94@cougarcs.com',
	// 	title: 'Faculty Advisor',
	// 	open: false,
	// 	show: true,
	// },
	{
		id: 1,
		name: 'Mariana Villalobos',
		image: mare,
		linkedin: 'https://www.linkedin.com/in/mariana07/',
		email: 'president@cougarcs.com',
		title: 'President',
		open: false,
		show: true,
	},
	{
		id: 2,
		name: 'Ibrahim Khatkhatay',
		image: ibrahim,
		linkedin: 'https://www.linkedin.com/in/ibrahim-khatkhatay/',
		email: 'vicepresident@cougarcs.com',
		title: 'Vice President',
		open: false,
		show: true,
	},
	{
		id: 3,
		name: 'Vyas Ramankulangara',
		image: vyas,
		linkedin: 'https://www.linkedin.com/in/vyas0189/',
		email: 'secretary@cougarcs.com',
		title: 'Secretary',
		open: false,
		show: true,
	},
	{
		id: 4,
		name: 'Chantha Mak',
		image: chantha,
		linkedin: 'https://www.linkedin.com/in/chantha-mak-830706177/',
		email: 'treasurer@cougarcs.com',
		title: 'Treasurer',
		open: false,
		show: true,
	},
	{
		id: 5,
		name: 'Shubh Sheth',
		image: user,
		linkedin: 'https://www.linkedin.com/in/sheth-shubh/',
		email: 'webmaster@cougarcs.com',
		title: 'Webmaster',
		open: false,
		show: true,
	},
	{
		id: 6,
		name: 'Sevilay Ozturk',
		image: user,
		linkedin: 'https://www.linkedin.com/in/sevilay-ozturkk/',
		email: 'communications@cougarcs.com',
		title: 'Director of Communications',
		open: false,
		show: true,
	},
	{
		id: 7,
		name: 'N/A',
		image: user,
		linkedin: 'N/A',
		email: 'N/A',
		title: 'Director of Operations',
		open: true,
		show: false,
	},
	{
		id: 8,
		name: 'Tooba Hashmi',
		image: user,
		linkedin: 'https://www.linkedin.com/in/tooba-hashmi-540a73156/',
		email: 'activities@cougarcs.com',
		title: 'Co-Director Of Activities',
		open: false,
		show: true,
	},
	{
		id: 9,
		name: 'Jerry Lopez',
		image: jerry,
		linkedin: 'https://www.linkedin.com/in/gerardo-lopez-374853181/',
		email: 'activities@cougarcs.com',
		title: 'Co-Director Of Activities',
		open: false,
		show: true,
	},
	{
		id: 10,
		name: 'Nykolas Farhangi',
		image: user,
		linkedin: 'https://www.linkedin.com/in/nykolasfarhangi/',
		email: 'tutoring@cougarcs.com',
		title: 'Director of Tutoring',
		open: false,
		show: true,
	},
];

export default officers;
