import chantha from './assets/chantha.JPG';
import ibrahim from './assets/ibes.JPG';
import jerry from './assets/jerry.JPG';
import mare from './assets/mariana.JPG';
import vyas from './assets/vyas.JPG';
import user from './assets/user.png';

const officers = [
	{
		id: 1,
		name: 'Mariana Villalobos',
		image: mare,
		linkedin: 'https://www.linkedin.com/in/mariana07/',
		email: 'mariana.villalobos@cougarcs.com',
		title: 'President',
		open: false,
		show: true,
	},
	{
		id: 2,
		name: 'Ibrahim Khatkhatay',
		image: ibrahim,
		linkedin: 'https://www.linkedin.com/in/ibrahim-khatkhatay/',
		email: 'i.khatkhatay@cougarcs.com',
		title: 'Vice President',
		open: false,
		show: true,
	},
	{
		id: 3,
		name: 'Vyas Ramankulangara',
		image: vyas,
		linkedin: 'https://www.linkedin.com/in/vyas0189/',
		email: 'vyas.r@cougarcs.com',
		title: 'Secretary',
		open: false,
		show: true,
	},
	{
		id: 4,
		name: 'Chantha Mak',
		image: chantha,
		linkedin: 'https://www.linkedin.com/in/chantha-mak-830706177/',
		email: 'chantha.mak@cougarcs.com',
		title: 'Treasurer',
		open: false,
		show: true,
	},
	{
		id: 5,
		name: 'N/A',
		image: user,
		linkedin: 'N/A',
		email: 'N/A',
		title: 'Webmaster',
		open: true,
		show: true,
	},
	{
		id: 6,
		name: 'N/A',
		image: user,
		linkedin: 'N/A',
		email: 'N/A',
		title: 'Director of Communications',
		open: true,
		show: true,
	},
	{
		id: 7,
		name: 'N/A',
		image: user,
		linkedin: 'N/A',
		email: 'N/A',
		title: 'Director of Operations',
		open: true,
		show: false,
	},
	{
		id: 8,
		name: 'N/A',
		image: user,
		linkedin: 'N/A',
		email: 'N/A',
		title: 'Co-Director Of Activities',
		open: true,
		show: true,
	},
	{
		id: 9,
		name: 'Jerry Lopez',
		image: jerry,
		linkedin: 'https://www.linkedin.com/in/gerardo-lopez-374853181/',
		email: 'gerardo.lopez@cougarcs.com',
		title: 'Acting Co-Director Of Activities',
		open: false,
		show: true,
	},
	{
		id: 10,
		name: 'N/A',
		image: user,
		linkedin: 'N/A',
		email: 'N/A',
		title: 'Director of Tutoring',
		open: true,
		show: true,
	},
];

export default officers;
